spring:
  cloud:
    gateway:
      routes:
        - id: TEST1_EUREKA_2
          uri: lb://TEST1-EUREKA-SERVICE
          predicates:
            - Path=/api/v1/test/**, /api/v1/first/**
        - id: TEST1_EUREKA
          uri: lb://TEST2-EUREKA-SERVICE
          predicates:
            - Path=/api/v1/test2/**
test-prop:
  value: Default_mode

RabitDetais: Normal  

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9090/eureka
