test-prop:
  value: Dev_mode
  retry: 4
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://localhost:9090/eureka
